services:
  backend:
    build:
      context: https://github.com/developmentHC/conectaBemBack.git
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: https://github.com/developmentHC/conectaBemFront.git
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:3000"
    env_file:
      - ./.env
    depends_on:
      - backend

  db:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
